### ISSUE TITLE
Unable to add to v1.0.3 to any project, regardless of framework version

### ISSUE THREAD

**Issue by nadinengland** [epiphanysearch/Epiphany.Core#2]
Tested adding v1.0.3 via nuget with no success on the following .NET framework version:

 - 4.5
 - 4.5.1
 - 4.5.2
 - 4.6
 - 4.6.1

v1.0.2 installs fine but then doesn't copy DLL into web folder on build (but I know this was fixed in v1.0.3 by [this commit](https://github.com/epiphanysearch/Epiphany.Core/commit/b450d2db16a45219d7734391b0a72b2b8605cba5).)

Nuget Error:

> Could not install package 'Epiphany.Core 1.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by StefanoChiodino** [comment]
Moved assembly to /lib, published 1.0.4, @nadinengland confirms to be working
